export const CAT_IDLE = [
  "....................",
  "............k...k...",
  "...........kpk.kpk..",
  "..........kppkkppk..",
  "..........kooooook..",
  "..k......kooogoogok.",
  ".kdk.....koooooooook",
  ".kdk....kdooowwppook",
  ".kok....kdoooowwdok.",
  "..kokkkkkdooooooodk.",
  "..koooooooooooooodk.",
  "..kowwwwwwwwwwwoodk.",
  "..kdowwwwwwwwwoodk..",
  "..kdoooooooooooodk..",
  "..kdokkdoodkkoodk...",
  "...kok..kok..kok....",
  "...kok..kok..kok....",
  "...kkk..kkk..kkk....",
];
export const CAT_RUN_A = [
  "....................",
  "............k...k...",
  "...........kpk.kpk..",
  "..........kppkkppk..",
  "..........kooooook..",
  "..k......kooogoogok.",
  ".kdk.....koooooooook",
  ".kdk....kdooowwppook",
  ".kok....kdoooowwdok.",
  "..kokkkkkdooooooodk.",
  "..koooooooooooooodk.",
  "..kowwwwwwwwwwwoodk.",
  "..kdowwwwwwwwwoodk..",
  "..kdoooooooooooodk..",
  ".kdookkdoodkkoodk...",
  "..kok...kok...kok...",
  ".kok.....kok...kok..",
  ".kkk.....kkk...kkk..",
];
export const CAT_RUN_B = [
  "....................",
  "............k...k...",
  "...........kpk.kpk..",
  "..........kppkkppk..",
  "..........kooooook..",
  "..k......kooogoogok.",
  ".kdk.....koooooooook",
  ".kdk....kdooowwppook",
  ".kok....kdoooowwdok.",
  "..kokkkkkdooooooodk.",
  "..koooooooooooooodk.",
  "..kowwwwwwwwwwwoodk.",
  "..kdowwwwwwwwwoodk..",
  "..kdoooooooooooodk..",
  "..kdokkdoodkkoodk...",
  "...kok..kok....kok..",
  "....kok..kok..kok...",
  "....kkk..kkk..kkk...",
];
export const CAT_JUMP = [
  "....................",
  "............k...k...",
  "...........kpk.kpk..",
  "..........kppkkppk..",
  "..........kooooook..",
  "..k......kooogoogok.",
  ".kdk.....koooooooook",
  ".kdk....kdooowwppook",
  ".kok....kdoooowwdok.",
  "..kokkkkkdooooooodk.",
  "..koooooooooooooodk.",
  "..kowwwwwwwwwwwoodk.",
  "..kdowwwwwwwwwoodk..",
  "..kdoooooooooooodk..",
  "..kdokkdoodkkoodk...",
  "..kok....kok...kok..",
  ".kok......kok...kok.",
  ".kkk......kkk...kkk.",
];
export const CAT_CLING = [
  "....................",
  "............k...k...",
  "...........kpk.kpk..",
  "..........kppkkppk..",
  "..........kooooook..",
  ".........kooogoogok.",
  "..k......koooooooook",
  ".kdk....kdooowwppook",
  ".kdk....kdoooowwdok.",
  ".kok.kkkkdooooooodk.",
  "..kokkooooooooooodk.",
  "..koowwwwwwwwwwoodk.",
  "..kdowwwwwwwwwoodk..",
  "..kdoooooooooooodk..",
  "..kdokkdoodkkoodk...",
  "...kok.kok...kok....",
  "...kok.kok...kok....",
  "...kkk.kkk...kkk....",
];
export const CAT_SPIN = [
  "....................",
  "....................",
  ".......kkkkkk.......",
  ".....kkooooooookk...",
  "....koooooooooook...",
  "...koooggoooggook...",
  "..kooooooooooooook..",
  ".kdoowwwwwwwwwoookd.",
  "kdoowwwwwwwwwwwoookd",
  ".kdoowwwwwwwwwoookd.",
  "..kooooooooooooook..",
  "...koooooooooooook..",
  "....kkoooooooookk...",
  ".......kkkkkk.......",
  "....................",
  "....................",
  "....................",
  "....................",
];
export const CAT_SLAM = [
  "....................",
  "........kkkk........",
  ".......kkppkk.......",
  "......kooooooook....",
  ".....koogoogook.....",
  ".....kooooooook.....",
  "....kdoowwwwoodk....",
  "....kdowwwwwwodk....",
  "...kdoowwwwwwoodk...",
  "...kdooowwwwooodk...",
  "....kdoooooooodk....",
  ".....kdoooooodk.....",
  "......kkooookk......",
  ".....kok.kok.kok....",
  ".....kok.kok.kok....",
  ".....kkk.kkk.kkk....",
  "....................",
  "....................",
];
export const CAT_SLIDE = [
  "........................",
  "..................kk....",
  "................kkppk...",
  "..kkk....kkkkkkkkoooook.",
  ".kdookkkkooooooooogoook.",
  ".kdoooooooooooooooooook.",
  "..kwwwwwwwwwwwwwwwwwwk..",
  "...kkkkkkkkkkkkkkkkkk...",
  "......k...k....k........",
];
export const HEDGEHOG = [
  "................",
  "....qqq..qqq....",
  "...qQqqqqQqqqq..",
  "..qQqqqqqqqQqqq.",
  ".qQqqqqqqqqqQqq.",
  ".qqqqqqqqqqqqqq.",
  "..knnnnnnnnnnnk.",
  "..knwnnnnnnnnpk.",
  "..knnnnnnnnnnnk.",
  "...knnnnnnnnnk..",
  "....kk....kk....",
  "....kk....kk....",
];
export const WASP = [
  "............",
  "..mm....mm..",
  "..mmm..mmm..",
  "...mmmmmm...",
  "..kzZzzZzk..",
  ".kzzZzzZzzk.",
  ".kzzZzzZzzk.",
  "..kzzzzzzk..",
  "...kkkkkk...",
  "......kk....",
];
export const BOSS = [
  "............................",
  "......kkkk..................",
  ".....kKKKKk.................",
  "....kKKKKKKk................",
  "...kKwKKKwKKk...............",
  "...kKwKKKwKKkkkkkkkkkkk.....",
  "...kKKKKKKKKKKKKKKKKKKKkk...",
  "...kKrKKKKKKKKKKKKKKKKKKKk..",
  "...kKKKKKKKKKKKKKKKKKKKKKKk.",
  "....kKKKKKKKKKKKKKKKKKKKKKk.",
  "....kOOKKKKKKKKKKKKKKKOOKKk.",
  "....kOOKKKKKKKKKKKKKKKOOKKk.",
  "....kKKKKKKKKKKKKKKKKKKKKKk.",
  "....kKKKKKKKKKKKKKKKKKKKKk..",
  "....kKKKkkkKKKKKKkkkKKKKKk..",
  "....kKKk...kKKKKk...kKKKk...",
  "....kKKk...kKKKKk...kKKKk...",
  "....kKKk...kKKKKk...kKKKk...",
  "....kkkk...kkkkkk...kkkkk...",
  "............................",
];
export const CRATE_PLAIN = [
  "kkkkkkkkkkkkkkkk",
  "kNNNNNNNNNNNNNNk",
  "kNMNNNNNNNNNNMNk",
  "kNNMNNNNNNNNMNNk",
  "kNNNMNNNNNNMNNNk",
  "kNNNNMNNNNMNNNNk",
  "kNNNNNMNNMNNNNNk",
  "kNNNNNNMMNNNNNNk",
  "kNNNNNNMMNNNNNNk",
  "kNNNNNMNNMNNNNNk",
  "kNNNNMNNNNMNNNNk",
  "kNNNMNNNNNNMNNNk",
  "kNNMNNNNNNNNMNNk",
  "kNMNNNNNNNNNNMNk",
  "kNNNNNNNNNNNNNNk",
  "kkkkkkkkkkkkkkkk",
];
export const CRATE_TNT = [
  "kkkkkkkkkkkkkkkk",
  "kRRRRRRRRRRRRRRk",
  "kRRRRRRRZRRRRRRk",
  "kRRRRRRZZRRRRRRk",
  "kRRRRZZZZZZRRRRk",
  "kRRRZZZZZZZZRRRk",
  "kRRZZZZZZZZZZRRk",
  "kRRZZZZwZZZZZRRk",
  "kRRZZZZZZZZZZRRk",
  "kRRZZZZZZZZZZRRk",
  "kRRRZZZZZZZZRRRk",
  "kRRRRZZZZZZRRRRk",
  "kRRRRRRRRRRRRRRk",
  "kRRRRRRRRRRRRRRk",
  "kRRRRRRRRRRRRRRk",
  "kkkkkkkkkkkkkkkk",
];
export const CRATE_NITRO = [
  "kkkkkkkkkkkkkkkk",
  "kXXXXXXXXXXXXXXk",
  "kXXXXXZZZZXXXXXk",
  "kXXXXZZZZZZXXXXk",
  "kXXXZZZZZZZZXXXk",
  "kXXXZwZZZZwZXXXk",
  "kXXXZwZZZZwZXXXk",
  "kXXXZZZZZZZZXXXk",
  "kXXXZZZZZZZZXXXk",
  "kXXXXZZZZZZXXXXk",
  "kXXXXXZZZZXXXXXk",
  "kXXXXZZZZZZXXXXk",
  "kXXXZZXZZXZZXXXk",
  "kXXXXXXXXXXXXXXk",
  "kXXXXXXXXXXXXXXk",
  "kkkkkkkkkkkkkkkk",
];
export const CRATE_BOUNCE = [
  "kkkkkkkkkkkkkkkk",
  "kLLLLLLLLLLLLLLk",
  "kLLLLLLZZLLLLLLk",
  "kLLLLLZZZZLLLLLk",
  "kLLLLZZZZZZLLLLk",
  "kLLLZZZZZZZZLLLk",
  "kLLLLLZZZZLLLLLk",
  "kLLLLLZZZZLLLLLk",
  "kLLLLLLLLLLLLLLk",
  "kLLLLLLZZLLLLLLk",
  "kLLLLLZZZZLLLLLk",
  "kLLLLZZZZZZLLLLk",
  "kLLLZZZZZZZZLLLk",
  "kLLLLLZZZZLLLLLk",
  "kLLLLLZZZZLLLLLk",
  "kkkkkkkkkkkkkkkk",
];
export const CRATE_CHECK = [
  "kkkkkkkkkkkkkkkk",
  "kPPPPPPPPPPPPPPk",
  "kPPPPPPPPPPPPPPk",
  "kPPZPPPPPPPPZPPk",
  "kPZZZPPPPPPZZZPk",
  "kPZZZZZZZZZZZZPk",
  "kPZwwZZZZZZwwZPk",
  "kPZwwZZZZZZwwZPk",
  "kPZZZZZZZZZZZZPk",
  "kPZZZZZppZZZZZPk",
  "kPZZZZZZZZZZZZPk",
  "kPPZZZZZZZZZZPPk",
  "kPPPZZZZZZZZPPPk",
  "kPPPPPPPPPPPPPPk",
  "kPPPPPPPPPPPPPPk",
  "kkkkkkkkkkkkkkkk",
];

/** Grids are authored facing right and doubled at bake time; see sprites.ts. */






export const DOG = [
  "....................",
  "..k.........kbbk....",
  ".kwk.......kbnnbk...",
  ".kwk......knnnnnnk..",
  ".kwk.....knnwwnnnnk.",
  ".kwk....kknwwwnnnnk.",
  "kwwwwwwwwwwwwwnnnnk.",
  "kwwwwwwwwwwwwwwwwrk.",
  "kwwbbbwwwwwwwwwwkkk.",
  "kwwbbbwwwwwwwwwk....",
  ".kwwwwwwwwwwwwwk....",
  ".kwkkwwkkkwwkkwk....",
  ".kwk.kwk..kwk.kwk...",
  ".kkk.kkk..kkk.kkk...",
];

export const DOG_SQUASHED = [
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "....................",
  "..kkkkkkkkkkkkkkkk..",
  ".kwwnnwwwwwwwwnnwwk.",
  ".kwwwwwwwwwwwwwwwwk.",
  "..kkkkkkkkkkkkkkkk..",
];

export const FLOWER = [
  "................",
  "....kkkkkkkk....",
  "...kppppppppk...",
  "...kpppyypppk...",
  "...kpppyypppk...",
  "...kppppppppk...",
  "....kkkkkkkk....",
  "......kAAk......",
  "..kAAkkAAk......",
  "......kAAkkAAk..",
  "......kAAk......",
  "......kkkk......",
];

export const FLAG = [
  ".....kkkkkkkkkk.",
  "...kkyyyyyyyyyk.",
  ".kkyyyyyyyyyyyk.",
  "kyyyyyyyyyyyyyk.",
  ".kkyyyyyyyyyyyk.",
  "...kkyyyyyyyyyk.",
  ".....kkkkkkkkkk.",
  "................",
];

export const GROUND = [
  "AAAAAAAAAAAAAAAA",
  "ABAABAAAABAAABAA",
  "BBBBBBBBBBBBBBBB",
  "CCDCCCCCDCCCCCCC",
  "CCCCCCCCCCCCCDCC",
  "CDCCCCCDCCCCCCCC",
  "CCCCCDCCCCCCCCDC",
  "CCCCCCCCCDCCCCCC",
  "DCCCCCCCCCCCDCCC",
  "CCCCDCCCCCCCCCCC",
  "CCCCCCCCDCCCCCCC",
  "CCDCCCCCCCCCCCDC",
  "CCCCCCCCCCDCCCCC",
  "CCCCDCCCCCCCCCCC",
  "CCCCCCCCCCCCCDCC",
  "DCCCCCCCDCCCCCCC",
];

export const DIRT = [
  "CCCCCCCCDCCCCCCC",
  "CCDCCCCCCCCCCCCC",
  "CCCCCCCCCCCDCCCC",
  "DCCCCCCCCCCCCCDC",
  "CCCCCDCCCCCCCCCC",
  "CCCCCCCCCCDCCCCC",
  "CDCCCCCCCCCCCCCC",
  "CCCCCCCDCCCCCCCC",
  "CCCCDCCCCCCCCCCC",
  "CCCCCCCCCCCCDCCC",
  "CCDCCCCCCCCCCCCC",
  "CCCCCCCCCDCCCCCC",
  "CCCCCCDCCCCCCCCC",
  "DCCCCCCCCCCCCCCC",
  "CCCCCCCCCCCCDCCC",
  "CCCDCCCCCCCCCCCC",
];

export const LOG = [
  "kkkkkkkkkkkkkkkk",
  "kEEEEEEEEEEEEEEk",
  "kEFFEEEEEEEFFEEk",
  "kEEEEEEEEEEEEEEk",
  "kEEEFFEEEEEEEEEk",
  "kEEEEEEEEEEFFEEk",
  "kEEEEEEEEEEEEEEk",
  "kFFFFFFFFFFFFFFk",
  "kkkkkkkkkkkkkkkk",
  "kEEEEEEEEEEEEEEk",
  "kEEFFEEEEEEEEEEk",
  "kEEEEEEEEEEEFFEk",
  "kEEEEEEEEEEEEEEk",
  "kEEEEFFEEEEEEEEk",
  "kFFFFFFFFFFFFFFk",
  "kkkkkkkkkkkkkkkk",
];

export const STUMP = [
  "kkkkkkkkkkkkkkkk",
  "kHHHHHHHHHHHHHHk",
  "kHIIIIIIIIIIIIJk",
  "kHIIkkkkkkkkIIJk",
  "kHIIkJJJJJJkIIJk",
  "kHIIkJkkkkJkIIJk",
  "kHIIkJkIIkJkIIJk",
  "kHIIkJkIIkJkIIJk",
  "kHIIkJkkkkJkIIJk",
  "kHIIkJJJJJJkIIJk",
  "kHIIkkkkkkkkIIJk",
  "kHIIIIIIIIIIIIJk",
  "kHIIIIIIIIIIIIJk",
  "kHJJJJJJJJJJJJJk",
  "kHJJJJJJJJJJJJJk",
  "kkkkkkkkkkkkkkkk",
];

export const CACTUS = [
  "................",
  "................",
  "......kkk.......",
  ".....kVVVk......",
  ".kkk.kVWVk......",
  "kVVk.kVVVk.kkk..",
  "kVWkkkVWVk.kVVk.",
  "kVVVVkVVVk.kVWk.",
  "kkVVVkVWVkkVVVk.",
  "..kVVkVVVkkVVk..",
  "...kkkVWVkkkk...",
  ".....kVVVk......",
  ".....kVVVk......",
  ".....kkkkk......",
];

/** Decorative only: these never enter the game state. */
export const BLOOM_A = [
  "..p...",
  ".pyp..",
  "..p...",
  "..A...",
  ".AA...",
  "..A...",
];

export const BLOOM_B = [
  ".w.w..",
  ".wyw..",
  "..A...",
  "..A...",
  ".A.A..",
  "..A...",
];

export const TUFT = [
  "......",
  "......",
  "A...A.",
  "A.A.A.",
  ".AAA..",
  "..A...",
];

export const CHERRY_TREE = [
  "......ppwpp.....",
  "....ppwppwpp....",
  "...pwppppppwp...",
  "..ppppwppwpppp..",
  ".pwpppppppppwp..",
  ".pppwppppwppppp.",
  "..pppppppppppp..",
  "...ppwpppwppp...",
  "....pppEppp.....",
  "......EEE.......",
  "......EFE.......",
  "......EEE.......",
  ".....EFEEF......",
  "....EEEEEEE.....",
];

/** Outro only: the cat's ride out to summer. */
export const BOAT = [
  "........k...............",
  "........kww.............",
  "........kwwww...........",
  "........kwwwwww.........",
  "........kwwwwwwww.......",
  "........kwwwwwwwwww.....",
  "........k...............",
  "........k...............",
  "kkkkkkkkkkkkkkkkkkkkkk..",
  "kEEEEEEEEEEEEEEEEEEEEk..",
  "kFEEEEEEEEEEEEEEEEEEFk..",
  ".kFFEEEEEEEEEEEEEEFFk...",
  "..kkFFFFFFFFFFFFFFkk....",
  "....kkkkkkkkkkkkkk......",
];

export const MONSTERA = [
  "..kkkk......kkkk..",
  ".kVVVVk....kVVVVk.",
  ".kVVVVVk..kVVVVVk.",
  "kVVVVVVk..kVVVVVVk",
  "kVVVkkVVkkVVVVVVVk",
  ".kkkkkVVGVVVVVVVVk",
  ".kkVVVVVGVVVkkkVVk",
  "kVVVVVVVGVVVVkkkk.",
  "kVkkkkVVGVVVVVVVk.",
  ".kkkVVVVGVVVkkVVVk",
  "kVVVVVVVGVVVkkkkk.",
  ".kVkkkVVGVVVVVVk..",
  "..kkkkVVGVVVVVVVk.",
  "..kVVVVVGVVVkkkk..",
  "..kVVkVVGVVVVk....",
  "...kkkVVGVVVVk....",
  ".....kVVGVVVk.....",
  "......kkVVkk......",
  "........kk........",
  "..................",
];

export const RAFT = [
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......k.........",
  "......k.........",
  "kkkkkkkkkkkkkkk.",
  "kEFEFEFEFEFEFEk.",
  "kkkkkkkkkkkkkkk.",
  "................",
];

export const SHIP = [
  "........k...............",
  "........kww.............",
  "........kwwww.....p.....",
  "........kwwwwww..pyp....",
  "........kwwwwwwww.p.....",
  "........kwwwwwwwwww.....",
  "..p.....k......p........",
  ".pyp....k.....pyp.......",
  "kkkkkkkkkkkkkkkkkkkkkk..",
  "kEEEEEEEEEEEEEEEEEEEEk..",
  "kFEEpEEEEpEEEEpEEEEpFk..",
  ".kFFEEEEEEEEEEEEEEFFk...",
  "..kkFFFFFFFFFFFFFFkk....",
  "....kkkkkkkkkkkkkk......",
];

export const SAND = [
  "SSSSSSSSSSSSSSSS",
  "SSSTSSSSSTSSSSSS",
  "SSSSSSSTSSSSSSTS",
  "STSSSSSSSSSTSSSS",
  "SSSSSTSSSSSSSSSS",
  "SSSSSSSSSTSSSSTS",
  "SSTSSSSSSSSSSSSS",
  "SSSSSSTSSSSTSSSS",
  "TSSSSSSSSSSSSSTS",
  "SSSSTSSSSSTSSSSS",
  "SSSSSSSSTSSSSSSS",
  "SSTSSSSSSSSSSSTS",
  "SSSSSSSSSSTSSSSS",
  "STSSSSTSSSSSSSSS",
  "SSSSSSSSSSSSTSSS",
  "SSSSTSSSSTSSSSSS",
];

export const DOG_SIT = [
  "....................",
  "..k.........kbbk....",
  ".kwk.......kbnnbk...",
  ".kwk......knnnnnnk..",
  ".kwk.....knnwwnnnnk.",
  ".kwk....kknwwwnnnnk.",
  ".kwkkkkkkwwwwwnnnnk.",
  ".kwwwwwwwwwwwwwwwrk.",
  "kwwbbbwwwwwwwwwwkkk.",
  "kwwbbbwwwwwwwwwk....",
  "kwwwwwwwwwwwwwwk....",
  "kwwwwwwwwwwwwwwk....",
  ".kwwkkwwwwwkkwwk....",
  ".kkk..kkkkk..kkk....",
];

export const RETRIEVER = [
  "........................",
  "................kkkk....",
  "..............kkYYYYk...",
  ".............kYYYYYYYk..",
  "..kk........kYYYYUYYYk..",
  ".kYYk......kYYUUYYYYYYk.",
  ".kYYYk....kkYUUUYYYYYYk.",
  ".kYYYYkkkkYYUUUYYYkkkkk.",
  "kYYYYYYYYYYYUUUYYkYYYYk.",
  "kYYYYYYYYYYYUUYYkkYYrYk.",
  "kYYYYYYYYYYYYYYYYkkkkkk.",
  ".kYYYYYYYYYYYYYYYk......",
  ".kUYYYYYYYYYYYYUUk......",
  ".kUUkkUUkkkUUkkUk.......",
  ".kUk..kUk..kUk.kUk......",
  ".kkk..kkk..kkk.kkk......",
  "........................",
  "........................",
];

export const RETRIEVER_SIT = [
  "........................",
  "................kkkk....",
  "..............kkYYYYk...",
  ".............kYYYYYYYk..",
  "..kk........kYYYYUYYYk..",
  ".kYYk......kYYUUYYYYYYk.",
  ".kYYYk....kkYUUUYYYYYYk.",
  ".kYYYYkkkkYYUUUYYYkkkkk.",
  ".kYYYYYYYYYYUUUYYkYYYYk.",
  ".kYYYYYYYYYYUUYYkkYYrYk.",
  "kYYYYYYYYYYYYYYYYkkkkkk.",
  "kYYYYYYYYYYYYYYYk.......",
  "kYYYYYYYYYYYYYYYk.......",
  ".kUUYYYYYYYYYUUUk.......",
  ".kUUkkUUUUUUkkUUk.......",
  ".kkk..kkkkkk..kkk.......",
  "........................",
  "........................",
];
